### ISSUE TITLE
Kilt crashing on 1.20.1 with forge and fabric mods

### ISSUE THREAD

**Issue by ollylr** [KiltMC/Kilt#85]
### Version information

Kilt-0.0.1+mc1.20.1+build.e4cef7.jar

### Reproduction Steps

1. Put fabric mods in folder
2. Run game (Works fine)
3. add forge mods
4. Crashes

### Java version

Java 8 Update 421

### Crash Report file

https://mclo.gs/sQrHpfs

### Additional information

![Screenshot 2024-11-24 154518](https://github.com/user-attachments/assets/7c79c9e8-98be-4595-8839-c5ad166ee0a9)
![image_2024-11-24_154610025](https://github.com/user-attachments/assets/a8bda708-f134-4575-8852-36277292ea74)

**Comment by Hellokhe** [comment]
what forge mods do you have

**Comment by ollylr** [comment]
> what forge mods do you have

i literally sent an attachment of my mods folder?

**Comment by ollylr** [comment]
> > what forge mods do you have
> 
> i literally sent an attachment of my mods folder?

i think im missing architechtury fabric or wtv for one of the dependencies but it hasnt said anything about it in the crash report thingy so

**Comment by Cartrigger** [comment]
Java 8 is a bit old for Minecraft 1.20.1... Most mods wont even start. Minecraft 1.17 requires Java 16 when 18 requires 17.
